'''create a hand cricker game using pygame consisting of numbers from 1 to 10 without using pygame and using tkinter for input and output
Rules:
1. If the number entered by the user matches the randomly generated number by the computer, the socre is increased by square of that number.
2. If the number entered by the user and the randomly number generated by the computer has a difference of 1, the batsman is out
3. 10 and 1 are considered adjacent numbers
4. If the numbers do not match and the difference is more than 1, the score increased by the number entered by the batsman
5. The game and declares the winner by which ever has the highest score after getting out
6. At the end of the game display the total score of the batsman
7. At first there will be a toss in which the user can choose heads or tails and if he wins the toss he can choose to bat or bowl first else the computer will choose randomly
'''
import tkinter as tk
from tkinter import messagebox
from tkinter import simpledialog
import random
def toss():
    user_choice = messagebox.askquestion("Toss", "Choose Heads or Tails (Yes for Heads, No for Tails)")
    toss_result = random.choice(['yes', 'no'])
    if user_choice == toss_result:
        messagebox.showinfo("Toss Result", "You won the toss!")
        bat_or_bowl = messagebox.askquestion("Choice", "Do you want to bat first? (Yes for Bat, No for Bowl)")
        return bat_or_bowl == 'yes'
    else:
        messagebox.showinfo("Toss Result", "Computer won the toss!")
        computer_choice = random.choice([True, False])
        return computer_choice
def play_innings(is_batting):
    score = 0
    while True:
        user_input = simpledialog.askinteger("Input", "Enter a number between 1 and 10:")
        if user_input is None or user_input < 1 or user_input > 10:
            messagebox.showerror("Error", "Invalid input! Please enter a number between 1 and 10.")
            continue
        computer_number = random.randint(1, 10)
        if user_input == computer_number:
            score += user_input ** 2
            messagebox.showinfo("Score Update", f"Matched! Score increased by {user_input ** 2}. Total Score: {score}")
        elif abs(user_input - computer_number) == 1 or (user_input == 1 and computer_number == 10) or (user_input == 10 and computer_number == 1):
            messagebox.showinfo("Out", f"You are out! Computer chose {computer_number}. Final Score: {score}")
            break
        else:
            score += user_input
            messagebox.showinfo("Score Update", f"No match! Score increased by {user_input}. Total Score: {score}")
    return score
def main():
    root = tk.Tk()
    root.withdraw()
    user_bats_first = toss()
    if user_bats_first:
        user_score = play_innings(True)
        computer_score = play_innings(False)
    else:
        computer_score = play_innings(False)
        user_score = play_innings(True)
    if user_score > computer_score:
        messagebox.showinfo("Game Over", f"You win! Your Score: {user_score}, Computer Score: {computer_score}")
    elif user_score < computer_score:
        messagebox.showinfo("Game Over", f"Computer wins! Your Score: {user_score}, Computer Score: {computer_score}")
    else:
        messagebox.showinfo("Game Over", f"It's a tie! Your Score: {user_score}, Computer Score: {computer_score}")
if __name__ == "__main__":
    main()
