'''create a hand cricker game using pygame consisting of numbers from 1 to 10
Rules:
1. If the number entered by the user matches the randomly generated number by the computer, the socre is increased by square of that number.
2. If the number entered by the user and the randomly number generated by the computer has a difference of 1, the batsman is out
3. 10 and 1 are considered adjacent numbers
4. If the numbers do not match and the difference is more than 1, the score increased by the number entered by the batsman
5. The game continues until the batsman is out
6. At the end of the game display the total score of the batsman
7. At first there will be a toss in which the user can choose heads or tails and if he wins the toss he can choose to bat or bowl first else the computer will choose randomly
'''
import pygame
import random
import sys
import time
pygame.init()
width, height = 600, 400
screen = pygame.display.set_mode((width, height))
pygame.display.set_caption("Crazy Hand Cricket")
font = pygame.font.Font(None, 36)
def draw_text(text, pos):
    text_surface = font.render(text, True, (255, 255, 255))
    screen.blit(text_surface, pos)
def toss():
    choices = ['Heads', 'Tails']
    user_choice = None
    while user_choice not in choices:
        screen.fill((0, 0, 0))
        draw_text("Choose Heads or Tails (H/T): ", (50, 150))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_h:
                    user_choice = 'Heads'
                elif event.key == pygame.K_t:
                    user_choice = 'Tails'
    computer_choice = random.choice(choices)
    toss_result = random.choice(choices)
    screen.fill((0, 0, 0))
    draw_text(f"You chose: {user_choice}", (50, 100))
    draw_text(f"Computer chose: {computer_choice}", (50, 150))
    draw_text(f"Toss result: {toss_result}", (50, 200))
    pygame.display.flip()
    time.sleep(2)
    if user_choice == toss_result:
        return 'User'
    else:
        return 'Computer'
def get_batting_choice(winner):
    if winner == 'User':
        choice = None
        while choice not in ['B', 'L']:
            screen.fill((0, 0, 0))
            draw_text("You won the toss! Choose to Bat or Bowl (B/L): ", (50, 150))
            pygame.display.flip()
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    sys.exit()
                if event.type == pygame.KEYDOWN:
                    if event.key == pygame.K_b:
                        choice = 'B'
                    elif event.key == pygame.K_l:
                        choice = 'L'
        return 'Bat' if choice == 'B' else 'Bowl'
    else:
        return random.choice(['Bat', 'Bowl'])
def play_game(batting_first):
    score = 0
    out = False
    while not out:
        screen.fill((0, 0, 0))
        draw_text(f"Current Score: {score}", (50, 50))
        draw_text("Enter your number (1-10): ", (50, 150))
        pygame.display.flip()
        user_number = None
        while user_number not in range(1, 11):
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    sys.exit()
                if event.type == pygame.KEYDOWN:
                    if event.key in [pygame.K_1, pygame.K_KP1]:
                        user_number = 1
                    elif event.key in [pygame.K_2, pygame.K_KP2]:
                        user_number = 2
                    elif event.key in [pygame.K_3, pygame.K_KP3]:
                        user_number = 3
                    elif event.key in [pygame.K_4, pygame.K_KP4]:
                        user_number = 4
                    elif event.key in [pygame.K_5, pygame.K_KP5]:
                        user_number = 5
                    elif event.key in [pygame.K_6, pygame.K_KP6]:
                        user_number = 6
                    elif event.key in [pygame.K_7, pygame.K_KP7]:
                        user_number = 7
                    elif event.key in [pygame.K_8, pygame.K_KP8]:
                        user_number = 8
                    elif event.key in [pygame.K_9, pygame.K_KP9]:
                        user_number = 9
                    elif event.key in [pygame.K_0, pygame.K_KP0]:
                        user_number = 10
        computer_number = random.randint(1, 10)
        screen.fill((0, 0, 0))
        draw_text(f"You chose: {user_number}", (50, 100))
        draw_text(f"Computer chose: {computer_number}", (50, 150))
        pygame.display.flip()
        time.sleep(2)
        if user_number == computer_number:
            score += user_number ** 2
        elif abs(user_number - computer_number) == 1 or (user_number == 1 and computer_number == 10) or (user_number == 10 and computer_number == 1):
            out = True
        else:
            score += user_number
    return score
def main():
    winner = toss()
    batting_first = get_batting_choice(winner)
    if batting_first == 'Bat':
        user_score = play_game('User')
        screen.fill((0, 0, 0))
        draw_text(f"You are out! Your total score: {user_score}", (50, 150))
        pygame.display.flip()
        time.sleep(2)
        computer_score = play_game('Computer')
        screen.fill((0, 0, 0))
        draw_text(f"Computer is out! Computer's total score: {computer_score}", (50, 150))
        pygame.display.flip()
        time.sleep(2)
    else:
        computer_score = play_game('Computer')
        screen.fill((0, 0, 0))
        draw_text(f"Computer is out! Computer's total score: {computer_score}", (50, 150))
        pygame.display.flip()
        time.sleep(2)
        user_score = play_game('User')
        screen.fill((0, 0, 0))
        draw_text(f"You are out! Your total score: {user_score}", (50, 150))
        pygame.display.flip()
        time.sleep(2)
    if user_score > computer_score:
        result = "You Win!"
    elif user_score < computer_score:
        result = "Computer Wins!"
    else:
        result = "It's a Tie!"
    screen.fill((0, 0, 0))
    draw_text(result, (250, 150))
    pygame.display.flip()
    time.sleep(3)
    pygame.quit()
    sys.exit()
if __name__ == "__main__":
    main()